[advisories]
version = 2
yanked = "deny"
ignore = [
  "RUSTSEC-2023-0071" # no solution is available
]

[bans]
deny = [
]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSL-1.0",
  "BSD-3-Clause",
  "LGPL-2.0-or-later",
  "MIT",
  "Unicode-3.0",
]
