pipeline:
  # Checks if minimal versions specified in Cargo.toml
  # are also valid.
  check-direct-minimal-versions:
    image: rust
    commands:
      - apt-get update -y -qq
      - apt-get install -y -qq --no-install-recommends clang make pkg-config nettle-dev libssl-dev pcscd libpcsclite-dev
      # This is available only in nightly for now:
      # https://github.com/rust-lang/cargo/pull/11688
      # FIXME: According to the PR linked it should be available in Cargo 1.70
      # CHECK: https://api.github.com/repos/rust-lang/rust/releases/latest->tag_name >= 1.70.0
      - rustup toolchain install nightly
      - cargo +nightly check -Zdirect-minimal-versions
