pipeline:
  e2e:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: ci/e2e.dockerfile
      # do not push
      dry_run: true
      # do not refresh image
      pull_image: false
      purge: false

  notify:
    image: rust
    secrets: [ codeberg_token ]
    commands:
      - export
      - bash ./ci/add-comment.sh "e2e"
    when:
      event: [ pull_request ]
      status: [ success, failure ]
