name: CI

on: [pull_request]

jobs:
  generate-matrix:
    name: Generate jobs
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.set-matrix.outputs.jobs }}
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@just
      - run: node ./scripts/ci/create-github-checks.js
        id: set-matrix

  run-task:
    name: ${{ matrix.jobs.doc }}
    runs-on: ubuntu-latest
    needs: [generate-matrix]
    container:
      image: archlinux
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix: ${{fromJSON(needs.generate-matrix.outputs.jobs)}}

    steps:
      - uses: actions/checkout@v6
      - run: pacman-key --init
      - run: pacman -Sy --needed --noconfirm archlinux-keyring
      - run: pacman -Syu --needed --noconfirm ${{ matrix.jobs.packages }}
      - run: just --justfile ${{ matrix.jobs.file }} ${{ matrix.jobs.name }}
