name: Nix

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-and-build:
     name: Run nix flake check and nix build
     runs-on: ${{ matrix.os }}
     continue-on-error: true
     strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
     steps:
       - uses: actions/checkout@v4
       - uses: nixbuild/nix-quick-install-action@v26
       - run: nix flake check
       - run: nix build .#pysequoia
